# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
